#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WarstwaUslug
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="Kasyno")]
	public partial class DataBaseDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertZdarzenie(Zdarzenie instance);
    partial void UpdateZdarzenie(Zdarzenie instance);
    partial void DeleteZdarzenie(Zdarzenie instance);
    partial void InsertRozegranaGra(RozegranaGra instance);
    partial void UpdateRozegranaGra(RozegranaGra instance);
    partial void DeleteRozegranaGra(RozegranaGra instance);
    partial void InsertGracz(Gracz instance);
    partial void UpdateGracz(Gracz instance);
    partial void DeleteGracz(Gracz instance);
    partial void InsertGra(Gra instance);
    partial void UpdateGra(Gra instance);
    partial void DeleteGra(Gra instance);
    #endregion
		
		public DataBaseDataContext() : 
				base(global::WarstwaUslug.Properties.Settings.Default.KasynoConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public DataBaseDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataBaseDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataBaseDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataBaseDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<Zdarzenie> Zdarzenie
		{
			get
			{
				return this.GetTable<Zdarzenie>();
			}
		}
		
		public System.Data.Linq.Table<RozegranaGra> RozegranaGra
		{
			get
			{
				return this.GetTable<RozegranaGra>();
			}
		}
		
		public System.Data.Linq.Table<Gracz> Gracz
		{
			get
			{
				return this.GetTable<Gracz>();
			}
		}
		
		public System.Data.Linq.Table<Gra> Gra
		{
			get
			{
				return this.GetTable<Gra>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Zdarzenie")]
	public partial class Zdarzenie : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _IdZdarzenia;
		
		private int _UczestnikGry;
		
		private int _UkonczonaGra;
		
		private double _Wygrana;
		
		private EntityRef<RozegranaGra> _RozegranaGra;
		
		private EntityRef<Gracz> _Gracz;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdZdarzeniaChanging(int value);
    partial void OnIdZdarzeniaChanged();
    partial void OnUczestnikGryChanging(int value);
    partial void OnUczestnikGryChanged();
    partial void OnUkonczonaGraChanging(int value);
    partial void OnUkonczonaGraChanged();
    partial void OnWygranaChanging(double value);
    partial void OnWygranaChanged();
    #endregion
		
		public Zdarzenie()
		{
			this._RozegranaGra = default(EntityRef<RozegranaGra>);
			this._Gracz = default(EntityRef<Gracz>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdZdarzenia", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int IdZdarzenia
		{
			get
			{
				return this._IdZdarzenia;
			}
			set
			{
				if ((this._IdZdarzenia != value))
				{
					this.OnIdZdarzeniaChanging(value);
					this.SendPropertyChanging();
					this._IdZdarzenia = value;
					this.SendPropertyChanged("IdZdarzenia");
					this.OnIdZdarzeniaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UczestnikGry", DbType="Int NOT NULL")]
		public int UczestnikGry
		{
			get
			{
				return this._UczestnikGry;
			}
			set
			{
				if ((this._UczestnikGry != value))
				{
					if (this._Gracz.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnUczestnikGryChanging(value);
					this.SendPropertyChanging();
					this._UczestnikGry = value;
					this.SendPropertyChanged("UczestnikGry");
					this.OnUczestnikGryChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UkonczonaGra", DbType="Int NOT NULL")]
		public int UkonczonaGra
		{
			get
			{
				return this._UkonczonaGra;
			}
			set
			{
				if ((this._UkonczonaGra != value))
				{
					if (this._RozegranaGra.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnUkonczonaGraChanging(value);
					this.SendPropertyChanging();
					this._UkonczonaGra = value;
					this.SendPropertyChanged("UkonczonaGra");
					this.OnUkonczonaGraChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Wygrana", DbType="Float NOT NULL")]
		public double Wygrana
		{
			get
			{
				return this._Wygrana;
			}
			set
			{
				if ((this._Wygrana != value))
				{
					this.OnWygranaChanging(value);
					this.SendPropertyChanging();
					this._Wygrana = value;
					this.SendPropertyChanged("Wygrana");
					this.OnWygranaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="RozegranaGra_Zdarzenie", Storage="_RozegranaGra", ThisKey="UkonczonaGra", OtherKey="IdRozegranejGry", IsForeignKey=true)]
		public RozegranaGra RozegranaGra
		{
			get
			{
				return this._RozegranaGra.Entity;
			}
			set
			{
				RozegranaGra previousValue = this._RozegranaGra.Entity;
				if (((previousValue != value) 
							|| (this._RozegranaGra.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._RozegranaGra.Entity = null;
						previousValue.Zdarzenie.Remove(this);
					}
					this._RozegranaGra.Entity = value;
					if ((value != null))
					{
						value.Zdarzenie.Add(this);
						this._UkonczonaGra = value.IdRozegranejGry;
					}
					else
					{
						this._UkonczonaGra = default(int);
					}
					this.SendPropertyChanged("RozegranaGra");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Gracz_Zdarzenie", Storage="_Gracz", ThisKey="UczestnikGry", OtherKey="IdGracza", IsForeignKey=true)]
		public Gracz Gracz
		{
			get
			{
				return this._Gracz.Entity;
			}
			set
			{
				Gracz previousValue = this._Gracz.Entity;
				if (((previousValue != value) 
							|| (this._Gracz.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Gracz.Entity = null;
						previousValue.Zdarzenie.Remove(this);
					}
					this._Gracz.Entity = value;
					if ((value != null))
					{
						value.Zdarzenie.Add(this);
						this._UczestnikGry = value.IdGracza;
					}
					else
					{
						this._UczestnikGry = default(int);
					}
					this.SendPropertyChanged("Gracz");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.RozegranaGra")]
	public partial class RozegranaGra : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _IdRozegranejGry;
		
		private int _Gra;
		
		private System.DateTime _CzasRozpoczeciaGry;
		
		private System.TimeSpan _CzasTrwaniaGry;
		
		private double _OplataWejsciowa;
		
		private double _MinimalnyDepozyt;
		
		private EntitySet<Zdarzenie> _Zdarzenie;
		
		private EntityRef<Gra> _Gra1;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdRozegranejGryChanging(int value);
    partial void OnIdRozegranejGryChanged();
    partial void OnGraChanging(int value);
    partial void OnGraChanged();
    partial void OnCzasRozpoczeciaGryChanging(System.DateTime value);
    partial void OnCzasRozpoczeciaGryChanged();
    partial void OnCzasTrwaniaGryChanging(System.TimeSpan value);
    partial void OnCzasTrwaniaGryChanged();
    partial void OnOplataWejsciowaChanging(double value);
    partial void OnOplataWejsciowaChanged();
    partial void OnMinimalnyDepozytChanging(double value);
    partial void OnMinimalnyDepozytChanged();
    #endregion
		
		public RozegranaGra()
		{
			this._Zdarzenie = new EntitySet<Zdarzenie>(new Action<Zdarzenie>(this.attach_Zdarzenie), new Action<Zdarzenie>(this.detach_Zdarzenie));
			this._Gra1 = default(EntityRef<Gra>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdRozegranejGry", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int IdRozegranejGry
		{
			get
			{
				return this._IdRozegranejGry;
			}
			set
			{
				if ((this._IdRozegranejGry != value))
				{
					this.OnIdRozegranejGryChanging(value);
					this.SendPropertyChanging();
					this._IdRozegranejGry = value;
					this.SendPropertyChanged("IdRozegranejGry");
					this.OnIdRozegranejGryChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Gra", DbType="Int NOT NULL")]
		public int Gra
		{
			get
			{
				return this._Gra;
			}
			set
			{
				if ((this._Gra != value))
				{
					if (this._Gra1.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnGraChanging(value);
					this.SendPropertyChanging();
					this._Gra = value;
					this.SendPropertyChanged("Gra");
					this.OnGraChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CzasRozpoczeciaGry", DbType="DateTime NOT NULL")]
		public System.DateTime CzasRozpoczeciaGry
		{
			get
			{
				return this._CzasRozpoczeciaGry;
			}
			set
			{
				if ((this._CzasRozpoczeciaGry != value))
				{
					this.OnCzasRozpoczeciaGryChanging(value);
					this.SendPropertyChanging();
					this._CzasRozpoczeciaGry = value;
					this.SendPropertyChanged("CzasRozpoczeciaGry");
					this.OnCzasRozpoczeciaGryChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CzasTrwaniaGry", DbType="Time NOT NULL")]
		public System.TimeSpan CzasTrwaniaGry
		{
			get
			{
				return this._CzasTrwaniaGry;
			}
			set
			{
				if ((this._CzasTrwaniaGry != value))
				{
					this.OnCzasTrwaniaGryChanging(value);
					this.SendPropertyChanging();
					this._CzasTrwaniaGry = value;
					this.SendPropertyChanged("CzasTrwaniaGry");
					this.OnCzasTrwaniaGryChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_OplataWejsciowa", DbType="Float NOT NULL")]
		public double OplataWejsciowa
		{
			get
			{
				return this._OplataWejsciowa;
			}
			set
			{
				if ((this._OplataWejsciowa != value))
				{
					this.OnOplataWejsciowaChanging(value);
					this.SendPropertyChanging();
					this._OplataWejsciowa = value;
					this.SendPropertyChanged("OplataWejsciowa");
					this.OnOplataWejsciowaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MinimalnyDepozyt", DbType="Float NOT NULL")]
		public double MinimalnyDepozyt
		{
			get
			{
				return this._MinimalnyDepozyt;
			}
			set
			{
				if ((this._MinimalnyDepozyt != value))
				{
					this.OnMinimalnyDepozytChanging(value);
					this.SendPropertyChanging();
					this._MinimalnyDepozyt = value;
					this.SendPropertyChanged("MinimalnyDepozyt");
					this.OnMinimalnyDepozytChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="RozegranaGra_Zdarzenie", Storage="_Zdarzenie", ThisKey="IdRozegranejGry", OtherKey="UkonczonaGra")]
		public EntitySet<Zdarzenie> Zdarzenie
		{
			get
			{
				return this._Zdarzenie;
			}
			set
			{
				this._Zdarzenie.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Gra_RozegranaGra", Storage="_Gra1", ThisKey="Gra", OtherKey="IdGry", IsForeignKey=true)]
		public Gra Gra1
		{
			get
			{
				return this._Gra1.Entity;
			}
			set
			{
				Gra previousValue = this._Gra1.Entity;
				if (((previousValue != value) 
							|| (this._Gra1.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Gra1.Entity = null;
						previousValue.RozegranaGra.Remove(this);
					}
					this._Gra1.Entity = value;
					if ((value != null))
					{
						value.RozegranaGra.Add(this);
						this._Gra = value.IdGry;
					}
					else
					{
						this._Gra = default(int);
					}
					this.SendPropertyChanged("Gra1");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Zdarzenie(Zdarzenie entity)
		{
			this.SendPropertyChanging();
			entity.RozegranaGra = this;
		}
		
		private void detach_Zdarzenie(Zdarzenie entity)
		{
			this.SendPropertyChanging();
			entity.RozegranaGra = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Gracz")]
	public partial class Gracz : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _IdGracza;
		
		private string _Imie;
		
		private string _Nazwisko;
		
		private System.DateTime _DataUrodzin;
		
		private EntitySet<Zdarzenie> _Zdarzenie;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdGraczaChanging(int value);
    partial void OnIdGraczaChanged();
    partial void OnImieChanging(string value);
    partial void OnImieChanged();
    partial void OnNazwiskoChanging(string value);
    partial void OnNazwiskoChanged();
    partial void OnDataUrodzinChanging(System.DateTime value);
    partial void OnDataUrodzinChanged();
    #endregion
		
		public Gracz()
		{
			this._Zdarzenie = new EntitySet<Zdarzenie>(new Action<Zdarzenie>(this.attach_Zdarzenie), new Action<Zdarzenie>(this.detach_Zdarzenie));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdGracza", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int IdGracza
		{
			get
			{
				return this._IdGracza;
			}
			set
			{
				if ((this._IdGracza != value))
				{
					this.OnIdGraczaChanging(value);
					this.SendPropertyChanging();
					this._IdGracza = value;
					this.SendPropertyChanged("IdGracza");
					this.OnIdGraczaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Imie", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string Imie
		{
			get
			{
				return this._Imie;
			}
			set
			{
				if ((this._Imie != value))
				{
					this.OnImieChanging(value);
					this.SendPropertyChanging();
					this._Imie = value;
					this.SendPropertyChanged("Imie");
					this.OnImieChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Nazwisko", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string Nazwisko
		{
			get
			{
				return this._Nazwisko;
			}
			set
			{
				if ((this._Nazwisko != value))
				{
					this.OnNazwiskoChanging(value);
					this.SendPropertyChanging();
					this._Nazwisko = value;
					this.SendPropertyChanged("Nazwisko");
					this.OnNazwiskoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DataUrodzin", DbType="Date NOT NULL")]
		public System.DateTime DataUrodzin
		{
			get
			{
				return this._DataUrodzin;
			}
			set
			{
				if ((this._DataUrodzin != value))
				{
					this.OnDataUrodzinChanging(value);
					this.SendPropertyChanging();
					this._DataUrodzin = value;
					this.SendPropertyChanged("DataUrodzin");
					this.OnDataUrodzinChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Gracz_Zdarzenie", Storage="_Zdarzenie", ThisKey="IdGracza", OtherKey="UczestnikGry")]
		public EntitySet<Zdarzenie> Zdarzenie
		{
			get
			{
				return this._Zdarzenie;
			}
			set
			{
				this._Zdarzenie.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Zdarzenie(Zdarzenie entity)
		{
			this.SendPropertyChanging();
			entity.Gracz = this;
		}
		
		private void detach_Zdarzenie(Zdarzenie entity)
		{
			this.SendPropertyChanging();
			entity.Gracz = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Gra")]
	public partial class Gra : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _IdGry;
		
		private string _NazwaGry;
		
		private string _InformacjeOGrze;
		
		private EntitySet<RozegranaGra> _RozegranaGra;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdGryChanging(int value);
    partial void OnIdGryChanged();
    partial void OnNazwaGryChanging(string value);
    partial void OnNazwaGryChanged();
    partial void OnInformacjeOGrzeChanging(string value);
    partial void OnInformacjeOGrzeChanged();
    #endregion
		
		public Gra()
		{
			this._RozegranaGra = new EntitySet<RozegranaGra>(new Action<RozegranaGra>(this.attach_RozegranaGra), new Action<RozegranaGra>(this.detach_RozegranaGra));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdGry", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int IdGry
		{
			get
			{
				return this._IdGry;
			}
			set
			{
				if ((this._IdGry != value))
				{
					this.OnIdGryChanging(value);
					this.SendPropertyChanging();
					this._IdGry = value;
					this.SendPropertyChanged("IdGry");
					this.OnIdGryChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NazwaGry", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string NazwaGry
		{
			get
			{
				return this._NazwaGry;
			}
			set
			{
				if ((this._NazwaGry != value))
				{
					this.OnNazwaGryChanging(value);
					this.SendPropertyChanging();
					this._NazwaGry = value;
					this.SendPropertyChanged("NazwaGry");
					this.OnNazwaGryChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_InformacjeOGrze", DbType="NVarChar(MAX) NOT NULL", CanBeNull=false)]
		public string InformacjeOGrze
		{
			get
			{
				return this._InformacjeOGrze;
			}
			set
			{
				if ((this._InformacjeOGrze != value))
				{
					this.OnInformacjeOGrzeChanging(value);
					this.SendPropertyChanging();
					this._InformacjeOGrze = value;
					this.SendPropertyChanged("InformacjeOGrze");
					this.OnInformacjeOGrzeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Gra_RozegranaGra", Storage="_RozegranaGra", ThisKey="IdGry", OtherKey="Gra")]
		public EntitySet<RozegranaGra> RozegranaGra
		{
			get
			{
				return this._RozegranaGra;
			}
			set
			{
				this._RozegranaGra.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_RozegranaGra(RozegranaGra entity)
		{
			this.SendPropertyChanging();
			entity.Gra1 = this;
		}
		
		private void detach_RozegranaGra(RozegranaGra entity)
		{
			this.SendPropertyChanging();
			entity.Gra1 = null;
		}
	}
}
#pragma warning restore 1591
